### PR TITLE
fix: Cast the initial values in the log to strings to be consistent with the ongoing values

### LINKED ISSUE #100: Parse updates from replication log into JSON values
When playing with the Getting Started guide in the README I noticed that after an update to the row with id 2, the 2 becomes "2". So probably something off with how we're parsing the replication log?

Screenshot 2024-07-17 at 3 25 42 PM

## Checklist
- [ ] update TODO example app to stop its special casing of string boolean values

### PR DESCRIPTION
**Pull request by robacourt**
Fixes #100

### CODE REVIEW

File: packages/sync-service/lib/electric/shapes/querying.ex [hunk 1]
```diff
@@ -25,4 +26,11 @@ defmodule Electric.Shapes.Querying do
 
     {query, stream}
   end
+
+  defp columns(root_table, conn) do
+    root_table
+    |> Inspector.load_table_info(conn)
+    |> Enum.map(&~s("#{&1.name}"::text))
```
Comment (icehaunter) [inline packages/sync-service/lib/electric/shapes/querying.ex:33]:
```suggestion
    |> Enum.map(&~s("#{Utils.escape_quotes(&1.name)}"::text))
```

and make `escape_quotes` public on `Utils` - otherwise this fails on a column with `"` in the name. Add  a test as well please!

**Review by icehaunter — CHANGES_REQUESTED** [review]
GJ and very concise change! I love it. One change request to safeguard the column names and we're golden.

**Review by icehaunter — APPROVED** [review]
